Fixed some issues

diff --git a/templates/openscap-oval-repost.sh.j2 b/templates/openscap-oval-repost.sh.j2
--- a/templates/openscap-oval-repost.sh.j2
+++ b/templates/openscap-oval-repost.sh.j2
@@ -1,17 +1,59 @@
-#!/bin/bash -e
+#!/bin/bash
 
-############################################################
-# Variables
-############################################################
+##############################################################
+#
+# Defining standard variables
+#
+##############################################################
 
-# Generic
-tmpdir=$(mktemp -d)
+# Set temporary PATH
+export PATH=/bin:/usr/bin:/sbin:/usr/sbin:$PATH
+
+# Get the name of the calling script
+FILENAME=$(readlink -f $0)
+BASENAME="${FILENAME##*/}"
+BASENAME_ROOT=${BASENAME%%.*}
+DIRNAME="${FILENAME%/*}"
+
+# Get name of symlink used to execute
+FILENAME1=$(realpath -s $0)
+BASENAME1="${FILENAME1##*/}"
+BASENAME1_ROOT=${BASENAME1%%.*}
+DIRNAME1="${FILENAME1%/*}"
+
+# Define temorary files, debug direcotory, config and lock file
+TMPDIR=$(mktemp -d)
+VARTMPDIR=/var/tmp
+TMPFILE=${TMPDIR}/${BASENAME}.${RANDOM}.${RANDOM}
+DEBUGDIR=${TMPDIR}/${BASENAME_ROOT}_${USER}
+CONFIGFILE=${DIRNAME}/${BASENAME_ROOT}.cfg
+LOCKFILE=${VARTMP}/${BASENAME_ROOT}.lck
+
+# Logfile & directory
+LOGDIR=$DIRNAME
+LOGFILE=${LOGDIR}/${BASENAME_ROOT}.log
+
+# Set date/time related variables
+DATESTAMP=$(date "+%Y%m%d")
+TIMESTAMP=$(date "+%Y%m%d.%H%M%S")
+
+# Figure out the platform
+OS=$(uname -s)
+
+# Get the hostname
+HOSTNAME=$(hostname -s)
+
+
+##############################################################
+#
+# Defining custom variables
+#
+##############################################################
 
 # OVAL file(s)
-
 openscap_url="{{ openscap_url }}"
-openscap_archive="$tmpdir/{{ openscap_url | basename }}"
-openscap_file="$tmpdir/{{ openscap_url | basename | regex_replace('\.bz2') }}"
+openscap_archive="$TMPDIR/{{ openscap_url | basename }}"
+openscap_file="$TMPDIR/{{ openscap_url | basename | regex_replace('\.bz2') }}"
 
 # Result file(s)
 openscap_report="{{ openscap_log_dir }}/oval-report-{{ inventory_hostname }}.html"
@@ -25,9 +67,47 @@ openscap_gpg_recipient="{{ openscap_gpg_recipient | default('') }}"
 openscap_sftp_upload_path="{{ openscap_sftp_upload_path | default('') }}"
 
 
-############################################################
-# Function
-############################################################
+##############################################################
+#
+# Defining standarized functions
+#
+#############################################################
+
+#FUNCTIONS=${DIRNAME}/functions.sh
+#if [[ -f ${FUNCTIONS} ]]
+#then
+#   . ${FUNCTIONS}
+#else
+#   echo "Functions file '${FUNCTIONS}' could not be found!" >&2
+#   exit 1
+#fi
+
+
+##############################################################
+#
+# Defining customized functions
+#
+#############################################################
+
+function Usage
+{
+
+  cat << EOF | grep -v "^#"
+
+$BASENAME
+
+Usage : $BASENAME <flags> <arguments>
+
+Flags :
+
+   -d|--debug   : Debug mode (set -x)
+   -D|--dry-run : Dry run mode
+   -h|--help    : Prints this help message
+   -v|--verbose : Verbose output
+
+EOF
+
+}
 
 function Download
 {
@@ -69,42 +149,65 @@ function Package_list
 
 }
 
-
-function Encrypt
-{
-
-  File1=$1
-  File2=${tmpdir}/$(basename $1).gpg
-
-  # Encrypt report using GPG
-  gpg --encrypt --armor \
-      --trust-model always \
-      --recipient ${openscap_gpg_recipient} \
-      --output ${File2} \
-      ${File1}
-
-}
-
-function Send_sftp
-{
-
-  # Upload the report & results
-  sftp -oBatchMode=no -b - openscap_server <<EOF
-lcd ${tmpdir}
-cd ${openscap_sftp_upload_path}
-put *.gpg
-bye
-EOF
-
-}
-
-############################################################
-# Main
-############################################################
+##############################################################
+#
+# Main programs
+#
+#############################################################
 
 # Make sure temporary files are cleaned at exit
-trap 'rm -fr ${tmpdir}' EXIT
+trap 'rm -fr ${TMPDIR}' EXIT
 trap 'exit 1' HUP QUIT KILL TERM INT
+
+# Set the defaults
+Debug_level=0
+Verbose=false
+Verbose_level=0
+Dry_run=false
+Echo=
+
+# parse command line into arguments and check results of parsing
+while getopts :dDhtv-: OPT
+do
+
+  # Support long options
+  if [[ $OPT = "-" ]] ; then
+    OPT="${OPTARG%%=*}"       # extract long option name
+    OPTARG="${OPTARG#$OPT}"   # extract long option argument (may be empty)
+    OPTARG="${OPTARG#=}"      # if long option argument, remove assigning `=`
+  fi
+
+  case $OPT in
+    d|debug)
+      Verbose=true
+      set -vx
+      ;;
+    D|dry-run)
+      Dry_run=true
+      Dry_run1="-D"
+      Echo=echo
+      ;;
+    h|help)
+      Usage
+      exit 0
+      ;;
+    t|transfer)
+      Transfer=true
+      ;;
+    v|verbose)
+      Verbose=true
+      ;;
+    *)
+      echo "Unknown flag -$OPT given!" >&2
+      exit 1
+      ;;
+  esac
+
+  # Set flag to be use by Test_flag
+  eval ${OPT}flag=1
+
+done
+shift $(($OPTIND -1))
 
 # Download latest OVAL
 echo "--- Download latest OVAL definitions"
@@ -117,18 +220,15 @@ Package_list
 echo "--- Create OpenSCAP report"
 Report
 
-# Encrypt report using GPG
-if [[ -n $openscap_gpg_recipient ]]
+# Send encrypted reports
+if [[ $Transfer == true ]]
 then
-  echo "--- Encrypt report & results using GPG"
-  Encrypt ${openscap_results}
-  Encrypt ${openscap_report}
-  Encrypt ${packages}
-  Encrypt ${repos}
-
-  # Upload the report & results
-  echo "--- Send encrypted report using SFTP"
-  Send_sftp
+  echo "--- Transferring files to remote server"
+  /usr/local/bin/file-transfer.sh \
+    ${openscap_results} \
+    ${openscap_report} \
+    ${packages} \
+    ${repos}
 fi
 
 # Exit now
